config/routes.rb
ManishHelpdesk::Application.routes.draw do

  devise_for :members

  resources :tickets, :only => [:index, :show,:update]
  resources :comments, :only => [:new, :create]

  root :to => 'tickets#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  belongs_to :ticket
  validates_presence_of :body
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :tickets, as: :assignable
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :body, :end_user_id, :title, :comment, :assignable_id
  has_many :comments
  belongs_to :assignable, polymorphic: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name
  has_many :tickets, as: :assignable
  has_many :comments, through: :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_member!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@ticket = Ticket.first
  	@comment = @ticket.comments.new
  end

  def create
  	@ticket = Ticket.first
  	@comment = @ticket.comments.new(params)
  	@comment.body = params[:body]
  	redirect_to tickets_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  	#@assignable = User.find(2)
  	#@tickets = @assignable.tickets
  	@tickets = Ticket.all
  end

  def show
  	@ticket = Ticket.find(params[:id])
    @author = @ticket.assignable_type.classify.constantize.find(@ticket.assignable_id).first_name
  	@comment = @ticket.comments.new
    @user = User.new
  end

  def update
  	@ticket = Ticket.find(params[:id])
    @author = @ticket.assignable_type.classify.constantize.find(@ticket.assignable_id)
    if (params[:ticket].has_key?(:comment))
      if(params[:ticket][:comment].has_key?(:body))
        @comment = @ticket.comments.new(params[:ticket][:comment])
        @comment.save      
        UserMailer.add_ticket(@author).deliver
        redirect_to ticket_path(params[:id])
      end
    end

    if (!params[:ticket].has_key?(:user))
      @ticket.assignable_id = User.find_by_first_name(params[:ticket][:user][:first_name]).id
      @ticket.save
      UserMailer.add_ticket(@author).deliver
      flash[:notice] = "Assigned to the respective User"
      redirect_to ticket_path(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/new.html.haml
%h1 Comments#new
%p Find me in app/views/comments/new.html.haml

app/views/confirmable/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManishHelpdesk</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" >
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">Help Desk</a>
			<div class="nav-collapse">
				<ul class="nav">
					<% if member_signed_in? %>
						<li>Signed in as <%= "#{current_member.email}" %></li>
						<li><%= link_to "Logout", destroy_member_session_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to "Login", new_member_session_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>
	<div class="container">
		<nav>
			<a href="/tickets">Tickets</a>
			<a href="#">Reports</a>
		</nav>
		<div class="span12"><%= yield %></div>
			
		</div>

	<% if flash[:notice] %>
		<div id="notice"><%= flash[:notice] %></div>
	<% end %>
<%= debug(params) if Rails.env.development? %>
	</div>
	
</body>
</html>

app/views/tickets/index.html.haml
%h1
  Tickets
  %h1
    #tickets
      - @tickets.each do |ticket|
        = link_to ticket.title, ticket_path(ticket)
        

app/views/tickets/show.html.haml
%h3 Assign To:
= form_for @ticket do |ticket_form|
	= ticket_form.fields_for @user do |user_fields|
		User: #{user_fields.text_field :first_name}
		%br
	= ticket_form.submit

%h3= @ticket.title
= simple_format @ticket.body
= @ticket.created_at
= simple_format @ticket.end_user_id
= simple_format @ticket.assignable_type
%p Comments
- @ticket.comments.each do |comment|
	%ul
		%li
			= comment.body
			%nbsp by 
			= @author
			= time_ago_in_words(@ticket.created_at)
			%nbsp ago

= form_for @ticket do |ticket_form|
	= ticket_form.fields_for @comment do |comment_fields|
		Comment: #{comment_fields.text_field :body}
		%br
	= ticket_form.submit